import Head from "next/head";
import { Inter } from "@next/font/google";
import SpacexIcon from "../components/SpacexIcon";
import SearchList from "../components/SearchList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section
          id="home"
          className="h-screen items-center justify-center flex gap-4 flex-col backdrop-blur-lg bg-black"
        >
          <div className="w-4/5 lg:w-1/2">
            <p className="w-fit p-4 text-center my-2 border border-white border-solid rounded shadow-xs shadow-white text-white">
              Get started with querying the spacex data
            </p>
            <div className="relative">
              <SpacexIcon />
              <SpacexIcon className="blur-md absolute top-0 left-0 w-full" />
            </div>
          </div>
          <div className="animate-bounce absolute bottom-10 bg-white dark:bg-slate-800 p-2 w-10 h-10 ring-1 ring-slate-900/5 dark:ring-slate-200/20 shadow-lg rounded-full flex items-center justify-center">
            <svg
              className="w-6 h-6 text-white"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path d="M19 14l-7 7m0 0l-7-7m7 7V3"></path>
            </svg>
          </div>
        </section>
        <section id="query-data" className="p-8 lg:p-16 !font-mono">
          <SearchList />
        </section>
      </main>
    </>
  );
}
